//! Opt-in integration of a Lithograph reference section into top-level
//! `AGENTS.md`/`CLAUDE.md`, so generated documentation is discoverable by
//! coding agents. `integrate_agents` is the *only* place in Lithograph that
//! writes to these files; `init`/`update` never touch them.

use std::path::{Path, PathBuf};

const AGENT_FILES: [&str; 2] = ["AGENTS.md", "CLAUDE.md"];
const BEGIN_MARKER: &str = "<!-- lithograph:begin -->";
const END_MARKER: &str = "<!-- lithograph:end -->";

/// What happened to one agent instruction file.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum AgentFileOutcome {
    /// The file had no Lithograph section yet; one was appended.
    Created,
    /// The file already had a Lithograph section with different content; it was replaced.
    Refreshed,
    /// The file already had an up-to-date Lithograph section; nothing changed.
    Unchanged,
}

/// Result for one processed agent instruction file.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct AgentFileResult {
    /// File that was processed.
    pub path: PathBuf,
    /// What happened to it.
    pub outcome: AgentFileOutcome,
}

/// Result of one `integrate-agents` run.
#[derive(Debug, Clone, PartialEq, Eq, Default)]
pub struct IntegrateAgentsReport {
    /// One entry per `AGENTS.md`/`CLAUDE.md` that exists at the repository root.
    pub results: Vec<AgentFileResult>,
}

/// Adds or refreshes the Lithograph reference section in whichever of
/// `AGENTS.md`/`CLAUDE.md` exist at `repo_root`. Files that don't exist are
/// left untouched (this command never creates a new instruction file from
/// scratch, only extends ones the project already has).
pub fn integrate_agents(repo_root: &Path) -> Result<IntegrateAgentsReport, std::io::Error> {
    let mut results = Vec::new();
    for filename in AGENT_FILES {
        let path = repo_root.join(filename);
        if !path.is_file() {
            continue;
        }

        let existing = std::fs::read_to_string(&path)?;
        let had_section = existing.contains(BEGIN_MARKER);
        let updated = upsert_section(&existing);

        let outcome = if updated == existing {
            AgentFileOutcome::Unchanged
        } else {
            std::fs::write(&path, &updated)?;
            if had_section {
                AgentFileOutcome::Refreshed
            } else {
                AgentFileOutcome::Created
            }
        };
        results.push(AgentFileResult { path, outcome });
    }
    Ok(IntegrateAgentsReport { results })
}

fn section_content() -> String {
    format!(
        "{BEGIN_MARKER}\n\
         ## Lithograph-generated documentation\n\
         \n\
         This repository has evidence-backed documentation generated by Lithograph:\n\
         \n\
         - Quickstart: `docs/lithograph/quickstart.md`\n\
         - Architecture: `docs/lithograph/architecture.md`\n\
         - Module pages: `docs/lithograph/modules/`\n\
         - Semantic graph: `.lithograph/graph/current.json`\n\
         - Page manifest: `.lithograph/manifest.json`\n\
         \n\
         Regenerate after making changes with `lithograph update <path>`.\n\
         {END_MARKER}\n"
    )
}

/// Replaces an existing marked section in place (preserving everything
/// else in the file byte-for-byte), or appends a new one when no section
/// exists yet.
fn upsert_section(existing: &str) -> String {
    if let Some(replaced) = replace_existing_section(existing) {
        return replaced;
    }

    let mut result = existing.to_owned();
    if !result.is_empty() {
        if !result.ends_with('\n') {
            result.push('\n');
        }
        result.push('\n');
    }
    result.push_str(&section_content());
    result
}

fn replace_existing_section(existing: &str) -> Option<String> {
    let start = existing.find(BEGIN_MARKER)?;
    let end_marker_offset = existing[start..].find(END_MARKER)?;
    let mut end = start + end_marker_offset + END_MARKER.len();
    if existing[end..].starts_with('\n') {
        end += 1;
    }

    let mut result = String::new();
    result.push_str(&existing[..start]);
    result.push_str(&section_content());
    result.push_str(&existing[end..]);
    Some(result)
}

#[cfg(test)]
mod tests {
    use super::{AgentFileOutcome, integrate_agents};

    #[test]
    fn creates_a_section_when_none_exists() -> Result<(), Box<dyn std::error::Error>> {
        let temp = tempfile::TempDir::new()?;
        std::fs::write(
            temp.path().join("AGENTS.md"),
            "# Agent instructions\n\nBe helpful.\n",
        )?;

        let report = integrate_agents(temp.path())?;

        assert_eq!(report.results.len(), 1);
        assert_eq!(report.results[0].outcome, AgentFileOutcome::Created);
        let content = std::fs::read_to_string(temp.path().join("AGENTS.md"))?;
        assert!(content.starts_with("# Agent instructions\n\nBe helpful.\n"));
        assert!(content.contains("<!-- lithograph:begin -->"));
        assert!(content.contains("docs/lithograph/quickstart.md"));

        Ok(())
    }

    #[test]
    fn second_run_is_a_no_op() -> Result<(), Box<dyn std::error::Error>> {
        let temp = tempfile::TempDir::new()?;
        std::fs::write(temp.path().join("CLAUDE.md"), "# Claude instructions\n")?;

        integrate_agents(temp.path())?;
        let after_first = std::fs::read_to_string(temp.path().join("CLAUDE.md"))?;
        let report = integrate_agents(temp.path())?;
        let after_second = std::fs::read_to_string(temp.path().join("CLAUDE.md"))?;

        assert_eq!(report.results[0].outcome, AgentFileOutcome::Unchanged);
        assert_eq!(after_first, after_second);

        Ok(())
    }

    #[test]
    fn refresh_replaces_the_section_in_place_and_preserves_surrounding_text()
    -> Result<(), Box<dyn std::error::Error>> {
        let temp = tempfile::TempDir::new()?;
        std::fs::write(
            temp.path().join("AGENTS.md"),
            "# Before\n\n\
             <!-- lithograph:begin -->\n\
             stale content that should be replaced\n\
             <!-- lithograph:end -->\n\n\
             # After\n\
             Keep this instruction.\n",
        )?;

        let report = integrate_agents(temp.path())?;

        assert_eq!(report.results[0].outcome, AgentFileOutcome::Refreshed);
        let content = std::fs::read_to_string(temp.path().join("AGENTS.md"))?;
        assert!(content.starts_with("# Before\n\n"));
        assert!(content.ends_with("# After\nKeep this instruction.\n"));
        assert!(!content.contains("stale content"));
        assert!(content.contains("docs/lithograph/quickstart.md"));

        Ok(())
    }

    #[test]
    fn skips_files_that_do_not_exist() -> Result<(), Box<dyn std::error::Error>> {
        let temp = tempfile::TempDir::new()?;

        let report = integrate_agents(temp.path())?;

        assert!(report.results.is_empty());

        Ok(())
    }

    #[test]
    fn processes_both_files_when_both_exist() -> Result<(), Box<dyn std::error::Error>> {
        let temp = tempfile::TempDir::new()?;
        std::fs::write(temp.path().join("AGENTS.md"), "# A\n")?;
        std::fs::write(temp.path().join("CLAUDE.md"), "# C\n")?;

        let report = integrate_agents(temp.path())?;

        assert_eq!(report.results.len(), 2);
        assert!(
            report
                .results
                .iter()
                .all(|result| result.outcome == AgentFileOutcome::Created)
        );

        Ok(())
    }
}
